part of 'main.dart';

// Longer phrases win; this order resolves ties between equally specific matches.
const Map<String, List<String>> categoryKeywords = {
  'Comisiones bancarias': [
    'comision',
    'comisiones',
    'comision bancaria',
    'comisiones bancarias',
    'cargo bancario',
    'cargos bancarios',
    'gastos bancarios',
    'tarifa bancaria',
    'mantenimiento de cuenta',
    'mantenimiento cuenta',
    'mantenimiento bancario',
  ],
  'Pago TDC': [
    'pago tdc',
    'pago de tdc',
    'pagar tdc',
    'abono tdc',
    'abono a tdc',
    'pago tarjeta',
    'pago de tarjeta',
    'pago de la tarjeta',
    'pagar tarjeta',
    'pagar la tarjeta',
    'abono tarjeta',
    'abono a tarjeta',
    'abono a la tarjeta',
    'pago minimo tdc',
    'pago minimo tarjeta',
    'pago minimo de tarjeta',
    'cuota tdc',
    'cancelar tdc',
    'cancelacion tdc',
    'deuda tdc',
  ],
  'Cuotas': [
    'cuota',
    'cuotas',
    'cashea',
    'krece',
    'weppa',
    'deuda',
    'deudas',
    'prestamo',
    'prestamos',
    'credito',
    'creditos',
    'financiamiento',
    'pago a plazos',
    'abono prestamo',
    'inicial compra',
  ],
  'Ahorro': [
    'ahorro',
    'ahorros',
    'ahorrar',
    'fondo de emergencia',
    'fondo emergencia',
    'fondo de reserva',
    'reserva de dinero',
    'alcancia',
    'guardar dinero',
    'guardar plata',
    'guardar',
    'apartado',
    'meta de ahorro',
  ],
  'La mamalona': [
    'la mamalona',
    'mamalona',
    'moto',
    'motos',
    'motocicleta',
    'motocicletas',
    'repuesto moto',
    'repuestos moto',
    'moto repuestos',
    'motorepuestos',
    'aceite moto',
    'caucho moto',
    'cauchos moto',
    'cadena moto',
    'bujia moto',
    'taller moto',
    'mecanico moto',
    'casco moto',
  ],
  'Transporte': [
    'transporte',
    'pasaje',
    'pasajes',
    'taxi',
    'taxis',
    'metro',
    'metrobus',
    'bus',
    'buses',
    'autobus',
    'autobuses',
    'camionetica',
    'camioneta',
    'mototaxi',
    'yummy rides',
    'yummyrides',
    'yummy ride',
    'ridery',
    'uber',
    'in drive',
    'indrive',
    'traslado',
    'traslados',
    'flete',
    'boleto',
    'boletos',
    'peaje',
    'peajes',
    'estacionamiento',
    'gasolina',
    'combustible',
    'diesel',
  ],
  'Salud': [
    'salud',
    'farmacia',
    'farmacias',
    'farmaceutico',
    'farmaceutica',
    'farmatodo',
    'farma todo',
    'farmarket',
    'farma market',
    'locatel',
    'farmahorro',
    'farma ahorro',
    'farmaciasaas',
    'farmacia saas',
    'medicamento',
    'medicamentos',
    'medicina',
    'medicinas',
    'remedio',
    'remedios',
    'pastilla',
    'pastillas',
    'jarabe',
    'vitamina',
    'vitaminas',
    'acetaminofen',
    'paracetamol',
    'ibuprofeno',
    'antibiotico',
    'antibioticos',
    'consulta medica',
    'consulta',
    'medico',
    'medica',
    'doctor',
    'doctora',
    'clinica',
    'hospital',
    'odontologo',
    'odontologia',
    'dentista',
    'laboratorio',
    'examen de sangre',
    'examenes medicos',
    'radiografia',
    'ecografia',
    'vacuna',
    'vacunas',
    'terapia',
    'fisioterapia',
    'psicologo',
    'oftalmologo',
    'optica',
    'seguro medico',
  ],
  'Delivery': [
    'delivery',
    'yummy',
    'yummy delivery',
    'pedidosya',
    'pedidos ya',
    'rappi',
    'entrega a domicilio',
    'envio a domicilio',
    'pedido a domicilio',
    'reparto',
    'repartidor',
    'mensajeria',
    'mandadito',
    'mandaditos',
  ],
  'Recarga saldo': [
    'recarga',
    'recargas',
    'recarga saldo',
    'recarga telefonica',
    'recarga movil',
    'saldo telefonico',
    'saldo movil',
    'saldo celular',
    'recarga movistar',
    'recarga digitel',
    'recarga movilnet',
    'movistar',
    'digitel',
    'movilnet',
    'prepago',
    'paquete de datos',
    'paquete datos',
    'megas',
    'saldo',
  ],
  'Suscripciones': [
    'suscripcion',
    'suscripciones',
    'subscripcion',
    'membresia',
    'streaming',
    'netflix',
    'spotify',
    'disney',
    'disney plus',
    'youtube premium',
    'youtube',
    'amazon prime',
    'prime video',
    'hbo',
    'hbo max',
    'max',
    'apple music',
    'apple tv',
    'icloud',
    'google one',
    'game pass',
    'xbox game pass',
    'playstation plus',
    'ps plus',
    'crunchyroll',
    'paramount',
    'deezer',
    'canva pro',
    'adobe',
    'chatgpt',
    'gimnasio',
    'gym',
  ],
  'Barbería': [
    'barberia',
    'barbero',
    'barber',
    'peluqueria',
    'peluquero',
    'corte de pelo',
    'corte pelo',
    'corte de cabello',
    'corte cabello',
    'cabello',
    'barba',
    'afeitado',
    'afeitar',
    'tinte',
    'peinado',
    'manicure',
    'pedicure',
    'manicura',
    'pedicura',
    'unas',
    'salon de belleza',
    'depilacion',
  ],
  'Educación': [
    'educacion',
    'colegio',
    'escuela',
    'liceo',
    'universidad',
    'instituto',
    'curso',
    'cursos',
    'clase',
    'clases',
    'matricula',
    'inscripcion escolar',
    'mensualidad colegio',
    'mensualidad escolar',
    'utiles',
    'utiles escolares',
    'libro',
    'libros',
    'cuaderno',
    'cuadernos',
    'fotocopia',
    'fotocopias',
    'papeleria',
    'tutoria',
    'diplomado',
    'seminario',
    'uniforme escolar',
  ],
  'Comida': [
    'comida',
    'comidas',
    'alimento',
    'alimentos',
    'alimentacion',
    'mercado',
    'supermercado',
    'automercado',
    'viveres',
    'despensa',
    'restaurante',
    'restaurant',
    'restaurantes',
    'almuerzo',
    'desayuno',
    'cena',
    'merienda',
    'arepa',
    'arepas',
    'empanada',
    'empanadas',
    'pizza',
    'pizzas',
    'hamburguesa',
    'hamburguesas',
    'sushi',
    'pollo',
    'carne',
    'pescado',
    'arroz',
    'pasta',
    'frutas',
    'verduras',
    'pan',
    'panaderia',
    'cafe',
    'cafeteria',
    'cachapa',
    'cachapas',
    'tequenos',
    'refresco',
    'jugo',
    'snack',
    'dulces',
    'helado',
    'agua mineral',
    'mcdonalds',
    'mcdonald s',
    'kfc',
    'burger king',
    'subway',
    'dominos',
    'domino s',
    'pizza hut',
    'arturos',
    'arturo s',
  ],
  'Servicios': [
    'servicios',
    'servicio',
    'wifi',
    'wi fi',
    'internet',
    'fibra',
    'fibra optica',
    'banda ancha',
    'cantv',
    'aba',
    'netuno',
    'inter',
    'simpletv',
    'simple tv',
    'thundernet',
    'airtek',
    'venet',
    'luz',
    'electricidad',
    'corpoelec',
    'agua',
    'hidrocapital',
    'hidrocentro',
    'hidrolago',
    'gas',
    'bombona',
    'gas domestico',
    'aseo',
    'aseo urbano',
    'recoleccion de basura',
    'television por cable',
    'tv cable',
    'telefono fijo',
  ],
  'Casa': [
    'casa',
    'hogar',
    'alquiler',
    'arrendamiento',
    'renta',
    'condominio',
    'apartamento',
    'vivienda',
    'hipoteca',
    'mueble',
    'muebles',
    'ferreteria',
    'plomero',
    'plomeria',
    'electricista',
    'pintura',
    'reparacion hogar',
    'limpieza',
    'detergente',
    'lavaplatos',
    'escoba',
    'decoracion',
    'electrodomestico',
    'nevera',
    'lavadora',
  ],
  'Compras': [
    'compra',
    'compras',
    'tienda',
    'ropa',
    'zapato',
    'zapatos',
    'calzado',
    'camisa',
    'pantalon',
    'vestido',
    'franela',
    'jeans',
    'accesorio',
    'accesorios',
    'perfume',
    'maquillaje',
    'regalo',
    'regalos',
    'celular',
    'telefono',
    'audifonos',
    'cargador',
    'computadora',
    'laptop',
    'amazon',
    'mercadolibre',
    'mercado libre',
    'shein',
    'temu',
    'aliexpress',
    'traki',
  ],
  'Otro': [
    'otro',
    'otros',
    'varios',
    'miscelaneo',
    'miscelaneos',
    'imprevisto',
    'imprevistos',
    'gasto general',
    'gastos generales',
    'sin categoria',
    'no clasificado',
  ],
};

String _categorySearchText(String value) =>
    normalizeText(value).replaceAll(RegExp(r'[^a-z0-9]+'), ' ').trim();

final _categoryPatterns = {
  for (final entry in categoryKeywords.entries)
    entry.key: RegExp('(?:^| )(${_categoryAlternatives(entry.value)})(?= |\$)'),
};

String _categoryAlternatives(List<String> words) {
  final phrases = words.map(_categorySearchText).toSet().toList()
    ..sort((a, b) => b.length.compareTo(a.length));
  return phrases.map(RegExp.escape).join('|');
}

String? categoryFromDescription(String value) {
  final text = _categorySearchText(value);
  if (text.isEmpty) return null;
  if (text == 'tdc' || text == 'tarjeta de credito') return 'Pago TDC';
  if (text == 'corte') return 'Barbería';
  String? category;
  var specificity = 0;
  for (final entry in _categoryPatterns.entries) {
    for (final match in entry.value.allMatches(text)) {
      final words = match.group(1)!.split(' ').length;
      if (words > specificity) {
        category = entry.key;
        specificity = words;
      }
    }
  }
  return category;
}

bool isBankCommissionCategory(String category) =>
    _categorySearchText(category) == 'comisiones bancarias';

bool isFeeExemptCategory(String category) =>
    _categorySearchText(category) == 'recarga saldo' ||
    isBankCommissionCategory(category);
